services:
  # Наша база данных будущего
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: universities_db
    ports:
      - "8000:8000"
    command: start --log debug --user ${SURREAL_USER} --pass ${SURREAL_PASS} memory # Для начала в памяти, потом прикрутишь volume
    restart: always

volumes:
  caddy_data:
  caddy_config:
