services:
  # Наша база данных будущего
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: universities_db
    ports:
      - "8000:8000"
    command: start --log info --user ${SURREAL_USER} --pass ${SURREAL_PASS} file:/data/surreal.db
    volumes:
      - surreal_data:/data
    restart: always

volumes:
  surreal_data:
  caddy_data:
  caddy_config:
